DROP DATABASE IF EXISTS trivia;
DROP USER IF EXISTS student;
CREATE DATABASE trivia ENCODING = 'UTF-8' TEMPLATE=TEMPLATE0;
CREATE USER student WITH ENCRYPTED PASSWORD 'student';
GRANT ALL PRIVILEGES ON DATABASE trivia TO student;
ALTER USER student CREATEDB;
ALTER USER student WITH SUPERUSER;